### ISSUE TITLE
ContainerIntrospectionBundle:DataCollector:container.html.twig template doesn't exist

### ISSUE THREAD

**Issue by bartekczyz** [steevanb/symfony-container-introspection#1]
Hi,

I'm using SF 4.1.4, just installed your bundle, but I get error:

```The profiler template "ContainerIntrospectionBundle:DataCollector:container.html.twig" for data collector "steevanb.container_collector" does not exist.```

**Comment by steevanb** [comment]
Should be fixed in `1.1.1`.

I worked on it on a project who have LiipThemeBundle installed, and i didn't see this problem with it.

Telle me if it's ok for you.

Thanks!

**Comment by bartekczyz** [comment]
It works like a charm, thanks
